jobs:
  - job: Install SSH key
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddy_known_hosts_entry)
          sshPublicKey: $(griddy_azure_public_key)
          sshPassphrase: $(griddy_azure_passphrase)
          sshKeySecureFile: "griddy_azure"
  - job: Linux
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - checkout: self
        submodules: true
        persistCredentials: true
      - script: |
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
          sudo apt update
          sudo apt install vulkan-sdk
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: .
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: --build . --config Release
        displayName: Build
      - script: |
          ctest .
        displayName: Test
