jobs:
  - job: Linux
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddle_known_hosts_entry)
          sshPublicKey: $(griddle_azure_public_key)
          sshPassphrase: $(griddle_azure_passphrase)
          sshKeySecureFile: griddle
      - checkout: self
        submodules: true
        persistCredentials: true
      - script: |
          set -ex
          wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-bionic.list http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.7
          sudo apt update
          sudo apt install vulkan-sdk
          vulkaninfo
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: . -DCMAKE_BUILD_TYPE=Release
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: --build .
        displayName: Build
      - script: |
          GTEST_OUTPUT=xml:test-report.xml ctest . --output-on-failure
        displayName: Test
        continueOnError: true
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: Ubuntu 18.04 Tests
        displayName: Publish Test Results
      - script: |
          set -ex
          python --version
          python3 --version
          cd python
          pip3 install wheel
          python3 setup.py bdist_wheel
        displayName: Build Python Wheel
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (test)"
        inputs:
          pythonUploadServiceConnection: pypitest
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test_deploy'))
      - task: TwineAuthenticate@1
        displayName: "Twine Authenticate (live)"
        inputs:
          pythonUploadServiceConnection: pypilive
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      - script: |
          pip3 install twine
          python3 -m twine upload --config-file $(PYPIRC_PATH) dist/*.whl
        displayName: Deploy To PyPi
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/test_deploy'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))


  - job: Windows
    variables:
      VULKAN_SDK: C:/VulkanSDK/1.2.135.0
    timeoutInMinutes: 20
    condition: false
    pool:
      vmImage: "windows-latest"
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddle_known_hosts_entry)
          sshPublicKey: $(griddle_azure_public_key)
          sshPassphrase: $(griddle_azure_passphrase)
          sshKeySecureFile: griddle
      - checkout: self
        submodules: true
        persistCredentials: true
      - bash: |
          set -ex
          curl -L -o "vulkan-installer.exe" "https://griddyvulkan.s3.amazonaws.com/VulkanSDK-1.2.135.0-Installer.exe"
          # This makes sure we wait for the vulkan SDK to complete installation
          _=$(echo "vulkan-installer.exe /S" | cmd)
          curl -L -o "vulkan-runtime.zip" "https://griddyvulkan.s3.amazonaws.com/vulkan-runtime-components.zip"
          unzip vulkan-runtime.zip
          cp VulkanRT-1.2.135.0-Components/x64/vulkaninfo.exe $VULKAN_SDK/Bin
          cp VulkanRT-1.2.135.0-Components/x64/vulkan-1.dll $VULKAN_SDK/Bin
        displayName: Installing Vulkan
      - bash: |
          set -ex
          export PATH=$PATH:/c/VulkanSDK/1.2.135.0/Bin
          echo $PATH
          cmake . -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
        displayName: Build
      - bash: |
          export PATH=$PATH:/c/VulkanSDK/1.2.135.0/Bin
          ./vulkaninfo
          export GTEST_OUTPUT=xml:test-report.xml
          ctest . -C Debug --output-on-failure
        continueOnError: true
        displayName: Test
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: Windows Tests
        displayName: Publish Test Results
      
  - job: MacOS
    timeoutInMinutes: 20
    pool:
      vmImage: "macOS-latest"
    condition: false
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: $(griddle_known_hosts_entry)
          sshPublicKey: $(griddle_azure_public_key)
          sshPassphrase: $(griddle_azure_passphrase)
          sshKeySecureFile: griddle
      - checkout: self
        submodules: true
        persistCredentials: true
      - bash: |
          set -ex
          curl -L -o "vulkan-installer.tar.gz" "https://griddyvulkan.s3.amazonaws.com/vulkansdk-macos-1.2.135.0.tar.gz"
          tar -xzf vulkan-installer.tar.gz
          cd vulkansdk-macos-1.2.135.0
          ./install_vulkan.py
        displayName: Installing Vulkan
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: . -DCMAKE_BUILD_TYPE=Debug
        displayName: Initialize CMake
      - task: CMake@1
        inputs:
          workingDirectory: .
          cmakeArgs: --build .
        displayName: Build
      - script: |
          GTEST_OUTPUT=xml:test-report.xml ctest . --output-on-failure
        displayName: Test
        continueOnError: true
      - task: PublishTestResults@2
        inputs:
          failTaskOnFailedTests: true
          testResultsFormat: JUnit # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: test-report.xml
          testRunTitle: MacOS Tests
        displayName: Publish Test Results
  
