jobs:
  - job: Linux
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: CMake@1
        inputs:
          cmakeArgs: --build . --config Release

      - script: |
        ctest .